.TH "src/auto.c" 3 "Fri Feb 20 2015" "Version 1.0" "josh's super legit robit code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/auto.c \- File for autonomous code\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBautonomous\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBbadPlan1\fP = false"
.br
.ti -1c
.RI "bool \fBgoodPlan1\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
File for autonomous code\&. 

This file should contain the user \fBautonomous()\fP function and any functions related to it\&. 
.SH "Function Documentation"
.PP 
.SS "void autonomous ()"
Runs autonomous code\&. 
.br
Contains code to run our autonomous plans\&. 
.br

.SH "Variable Documentation"
.PP 
.SS "bool badPlan1 = false"
Determines if we should run our bad autonomous plan\&. 
.SS "bool goodPlan1 = true"
Determines if we should run our good autonomous plan\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for josh's super legit robit code from the source code\&.
