.TH "src Directory Reference" 3 "Mon Mar 2 2015" "Version 1.0" "josh's super legit robit code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauto\&.c\fP"
.br
.RI "\fIFile for autonomous code\&. \fP"
.ti -1c
.RI "file \fBinit\&.c\fP"
.br
.RI "\fIFile for initialization code\&. \fP"
.ti -1c
.RI "file \fBopcontrol\&.c\fP"
.br
.RI "\fIFile for operator control code\&. \fP"
.in -1c
